apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  params:
    - name: "random-number"
      default: "random-number not provided"
  steps:
    - name: goodbye
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo "Goodbye World!"
        echo "Random number from previous step: $(params.random-number)"
