apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push-events-trigger
      interceptors:
        - name: "verify-github-payload"
          ref:
            name: "github"
            kind: ClusterInterceptor
          params:
            - name: secretRef
              value:
                secretName: "github-secret"
                secretKey: "secretToken"
            - name: eventTypes
              value:
                - "pull_request"
        - name: "only when PRs are opened"
            ref:
              name: "cel"
            params:
              - name: "filter"
                value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - name: git-revision
          value: $(body.pull_request.head.sha)
        - name: git-repository-url
          value: $(body.repository.clone_url)
      template:
        spec:
          params:
            - name: git-revision
            - name: git-repository-url
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: show-parameter-triggered-pipeline-
              spec:
                pipelineRef:
                  name: show-parameter-pipeline
                params:
                  - name: image
                    value: test-image-build-by-buildpack-and-triggered:latest
                  - name: git-repository-url
                    value: $(tt.params.git-repository-url)
                  - name: git-revision
                    value: $(tt.params.git-revision)

