apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tekton-triggers
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tekton-triggers
  dependsOn:
  - name: tekton-ci-config
  prune: true
  validation: client
  targetNamespace: tekton-pipelines
